# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/cmpe140/mips_processor/mips_processor.cache/wt [current_project]
set_property parent.project_path F:/cmpe140/mips_processor/mips_processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/cmpe140/mips_processor/mips_processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/memfileLab7.dat
read_verilog -library xil_defaultlib {
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/adder.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/alu.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/auxdec.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/button_debouncer.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/clk_gen.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/controlunit.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/datapath.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/dmem.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/dreg.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/hex_to_7seg.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/imem.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/led_mux.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/maindec.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mips.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mips_top.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/multiplier.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mux2.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mux3.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mux6.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/regfile.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/shifter.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/signext.v
  F:/cmpe140/mips_processor/mips_processor.srcs/sources_1/new/mips_fpga.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/cmpe140/mips_processor/mips_processor.srcs/constrs_1/new/mips_fpga.xdc
set_property used_in_implementation false [get_files F:/cmpe140/mips_processor/mips_processor.srcs/constrs_1/new/mips_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mips_fpga -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_fpga_utilization_synth.rpt -pb mips_fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
